In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [4]:
# Python List
a = [1,2,3]
b = [4,5,6]

In [5]:
print(a+b)

[1, 2, 3, 4, 5, 6]


In [6]:
v = np.array(a)
v

array([1, 2, 3])

In [7]:
m = np.array([a,b])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

b: add cell bellow\
a: add cell above\
m: markdown\
double d: delete\
shift+enter: run
![](path): add image


In [9]:
print('hello')

hello


In [10]:
v.shape

(3,)

In [11]:
m.shape

(2, 3)

In [12]:
v.size

3

In [13]:
m.size

6

In [14]:
m.dtype

dtype('int64')

In [15]:
v.dtype

dtype('int64')

In [16]:
zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [17]:
zeros_matrix2 = np.zeros((5,2))

zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
zeros_matrix3 = np.zeros((3,4,2)) #row,col,dept
zeros_matrix3

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
a = [10, 11, 12]
b = [14, 15, 16]
c = [17, 18, 19]
d = [20, 21, 22]
m = np.array([a,b,c,d])

m

array([[10, 11, 12],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [20]:
m2 = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
m2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

In [21]:
m2 = np.array([[2,7],[3,9],[4,0],[3,9],[4,0]])
m2.size

10

In [22]:
a2 = [10, 11, 12, 13, 14]
b2 = [14, 15, 16, 17, 18]
m3 = np.array([a2,b2])
m3.size

10

In [78]:
matrix3D = np.array([[[1, 2, 1], [3, 4, 3], [3, 4, 3] ], 
                       [[5, 6, 5], [7, 8, 7], [3, 4, 3]]])
matrix3D.shape

(2, 3, 3)

In [44]:
m3 = np.ones((2,3,3))
m3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [71]:
matrix = np.zeros((5,3))
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        matrix[i,j] = 2  

matrix

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [76]:
matrix = matrix.astype('int32') 

In [77]:
matrix

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [79]:
matrix5 = np.zeros((5,3))
for i in matrix5:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


#Day-2

In [81]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [83]:
x = np.arange(10, 20) # start, stop
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
x = np.arange(10, 20, 2) #start, stop, step
x

array([10, 12, 14, 16, 18])

In [86]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [88]:
#linspace 

np.linspace(0, 10, 20) #membuat sampel 0-10 sebanyak 20

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [91]:
#random data

from numpy import random

In [93]:
np.random.rand(5,5)

array([[0.46727894, 0.0524568 , 0.44558748, 0.34030749, 0.36034585],
       [0.58091669, 0.3121833 , 0.84821554, 0.0056132 , 0.80445635],
       [0.54296387, 0.01026901, 0.01990879, 0.4497891 , 0.80176258],
       [0.37269185, 0.28081014, 0.54641054, 0.99737342, 0.17035346],
       [0.50113143, 0.4281359 , 0.26830172, 0.42097721, 0.37593735]])

In [92]:
random.rand(5,5) #range 0-1

array([[0.37959576, 0.54922238, 0.76238061, 0.0188941 , 0.94339227],
       [0.99442836, 0.32332551, 0.2109266 , 0.87874618, 0.9958583 ],
       [0.37388663, 0.38251039, 0.30138832, 0.46606972, 0.77499699],
       [0.34268418, 0.45708594, 0.28445259, 0.18384366, 0.96510373],
       [0.13660429, 0.50028641, 0.38232762, 0.04782796, 0.662508  ]])

In [94]:
x = random.randn(5,5) #terdistribusi normal
x

array([[ 1.42888322,  1.15451902, -1.27139737,  0.26112072, -0.16797481],
       [ 0.0600097 ,  1.3599396 , -0.9559795 , -1.16903427,  0.65195286],
       [ 0.83946748,  0.43436034,  1.17601638,  1.26112722,  1.42095035],
       [-1.63661643, -0.09190003,  0.65966119,  0.11269624,  0.7159743 ],
       [-0.02837552, -1.42726007,  0.56118859,  1.08840564, -0.47424887]])

In [95]:
x.dtype

dtype('float64')

In [96]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [97]:
random.randint(10) #random integer 

2

In [100]:
random.randint(2,10, size=4) #2-10 sizenya 4

array([9, 6, 6, 5])

In [103]:
random.randint(2,10, size=(4,2,2))

array([[[3, 7],
        [7, 9]],

       [[7, 3],
        [2, 4]],

       [[3, 2],
        [3, 8]],

       [[6, 4],
        [3, 8]]])

In [107]:
m1 = random.randint(0,100, size=5)
m1

array([12,  7, 66, 86, 93])

In [111]:
m2 = random.randint(0,100, size=(3,5))
m2

array([[ 7, 30, 46, 62,  2],
       [19, 84,  7, 32, 38],
       [29, 51, 40, 37, 58]])

In [115]:
m3 = np.linspace(1.5, 5.5, 30)
m3

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

In [116]:
#append
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.append(my_arr, (10,11,12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
my_arr1 = np.array([[1,2,3],
                   [2,4,6]])

In [119]:
np.append(my_arr1, [[2,1,1]], axis=0)

array([[1, 2, 3],
       [2, 4, 6],
       [2, 1, 1]])

In [120]:
a = np.array([[1,2,3],[2,4,6]])
b = np.array([[1,2,3],[2,4,6]])
np.concatenate((a,b))

array([[1, 2, 3],
       [2, 4, 6],
       [1, 2, 3],
       [2, 4, 6]])

In [ ]:
np.delete(arr, 1, axis=0) //baris

In [121]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [123]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
m1 = random.randint(2,10, size=9)
m1.reshape(3,3) 

array([[6, 2, 8],
       [4, 6, 3],
       [5, 7, 6]])

In [141]:
a = np.array([[0,1,3],[5,7,9]])
b = np.array([[0,2,4],[6,8,10]])

c = np.concatenate((a,b), axis = 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [167]:
a = np.array([1,2,3,4,5,6])
a.shape
a

array([1, 2, 3, 4, 5, 6])

In [168]:
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

In [169]:
a2 = a[:, np.newaxis]
a2.shape

(6, 1)

In [170]:
b = np.expand_dims(a, axis=0)
b.shape

(1, 6)

In [171]:
data = np.array([1,2,3,4,5])
data[1]

2

In [172]:
data[:3]

array([1, 2, 3])

In [173]:
data[1:]

array([2, 3, 4, 5])

In [176]:
data[-2:]

array([4, 5])

In [175]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [5,7,9,3]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 7, 9, 3]])

In [177]:
print(a[a<5])

[1 2 3 4 3]


In [178]:
print(a[a%2==0])

[2 4 6 8]


In [179]:
a[1,1:3] #baris 1, colom 1-3

array([6, 7])

In [183]:
matrix3D = np.array([[[1, 2, 1], [3, 4, 100], [3, 4, 3] ], 
                       [[5, 6, 5], [7, 8, 7], [3, 4, 3]]])
matrix3D

array([[[  1,   2,   1],
        [  3,   4, 100],
        [  3,   4,   3]],

       [[  5,   6,   5],
        [  7,   8,   7],
        [  3,   4,   3]]])

In [184]:
matrix3D[0]

array([[  1,   2,   1],
       [  3,   4, 100],
       [  3,   4,   3]])

In [185]:
matrix3D[0,1]

array([  3,   4, 100])

In [187]:
matrix3D[1,1,:]

array([7, 8, 7])

In [188]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
a[5] = 12

In [192]:
a

array([ 0,  1,  2,  3,  4, 12,  6,  7,  8,  9])