In [1]:
import numpy as np

## > Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [2]:
a = np.zeros(10)
print("null vector/1D size 10:\n",a)
a[5] = 11
print("\nUpdate fifth value to 11:\n",a)

null vector/1D size 10:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update fifth value to 11:
 [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [3]:
b = np.arange(6).reshape(2,3)
print("array 2x3:\n", b)
c = b.reshape(3,2)
print("\narray 3x2:\n", c)

array 2x3:
 [[0 1 2]
 [3 4 5]]

array 3x2:
 [[0 1]
 [2 3]
 [4 5]]


3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [22]:
d = np.ones((5,5))
print("matrix ones 2D:\n", d)
d[1:4,1:4] = 0
print("\n1 on the border and 0 inside in the array:\n", d)

matrix ones 2D:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


4. Take a look at the following matrix. Access the [2, 1,1]

In [5]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z[2,1,1]

2

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3

In [6]:
y = np.zeros((4,4))
y += np.arange(4)
y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis

In [7]:
y = np.arange(16).reshape((4, 4))
print("array 4x4:\n" , y)
y1 = np.hsplit(y,2)
print("\nturn it into two arrays along the second axis:\n", y1)

array 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

turn it into two arrays along the second axis:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
